# Elliot's zsh config file

# Load aliases, funcs, and envvariables
[ -f "$HOME/.config/envvariables" ] && source "$HOME/.config/envvariables"
[ -f "$HOME/.config/aliases" ] && source "$HOME/.config/aliases"
[ -f "$HOME/.config/funcs" ] && source "$HOME/.config/funcs"

# Set zsh theme
ZSH_THEME="robbyrussell"

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
#HISTFILE=~/.cache/history
HISTFILE=~/history

## History command configuration
#setopt extended_history       # record timestamp of command in HISTFILE
#setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
#setopt hist_ignore_dups       # ignore duplicated commands history list
#setopt hist_ignore_space      # ignore commands that start with space
#setopt hist_verify            # show command with history expansion to user before running it
#setopt inc_append_history     # add commands to HISTFILE in order of execution
#setopt share_history          # share command history data

plugins=(git github zsh-syntax-highlighting vi-mode)
source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='vi'
 fi

# added by Anaconda3 2018.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/trapp/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/trapp/anaconda3/etc/profile.d/conda.sh" ]; then
# . "/home/trapp/anaconda3/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/trapp/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/etrapp/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/etrapp/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/etrapp/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/etrapp/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Set conda environement
py3_env

